# Generated by Django 4.2.5 on 2023-10-31 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='publication_date',
            new_name='publish_date',
        ),
    ]
